### ISSUE TITLE
Proofread English PML Specs

### ISSUE THREAD

**Issue by tajmone** [tajmone/polygen-docs#17]
The English _[PML Spec 1.0][PML EN]_ documentation (Ed. `v1.1.0`, 2018/02/10) contains a considerable number of typos and spurious paragraphs left over from the editing stage (either the original Italian text or alternative translations that were accidentally left behind).

### Live Previews

Up-to-date Live HTML Previews of the `v1.1.1` release candidate (WIP), directly from the dev branche, will be available at this link:

- [English **PML Spec** 1.1.1-rc preview][PML EN-rc]

Whenever a fix is applied to the source doc, the HTML document will be rebuild to ensure that proofreaders have access to on-line previews of the latest edited version of each document.

### Current Work Plan

I've already started to track the various issues under the <kbd>[PML Spec EN v1.1.1][PML EN v1.1.1]</kbd> milestone and I'm planning an updated edition (Ed. `v1.1.1`). Obviously the Spec version remains the same (PML 1.0), it's just the document edition that's being updated, and this will not introduce new contents but just fix the existing ones.

All fixes and updates for the English doc will be commited to the [`dev1.1.1_EN`][dev1.1.1_EN] branch, and ultimately squashed as a single commit on `master` when it's ready.

### Needed Support

I would really appreciate some help with the revision of the English text, i.e. searching for linguistic typos, stray paragraphs and any problems with the examples (PML source and their productions) and the pointing them out by creating new Issues here.

> __NOTE__ — For convenience, we'll adopt `en_US` dictionaries for proofreading, since many programming terms have become standard in theri US form even in the UK.

@alvisespano, if you could double check all the examples (both sources and productions) it would be really helpful. Many examples were re-adapted by myself in occasion of the new markdown edition of the Specs, in an attempt to make them "more English", so chances are that in various occasions I might have gotten the productions samples wrong (e.g. in one case, I forgot to translate some Italian words).

@RBastianini, I was wondering if you'd like to help in this revision work, since the English PML Specs also apply to your __[Polygen-PHP]__ project, since it's 100% Polygen compliant — b.t.w., excellent work there! well done.

[PML EN]: http://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/master/polygen-spec_EN.html

[PML EN v1.1.1]: https://github.com/tajmone/polygen-docs/milestone/1
[Polygen-PHP]: https://github.com/RBastianini/polygen-php

[PML EN-rc]: https://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/dev1.1.1_EN/docs-src/polygen-spec_EN.html "Live HTML Preview of the English PML Spec 1.1.1 release candidate"

[dev1.1.1_EN]: https://github.com/tajmone/polygen-docs/tree/dev1.1.1_EN "View branch 'dev1.1.1_EN' on GitHub"

**Comment by RBastianini** [comment]
I'd be happy to. I might have a couple of free evening this coming wee. Do you want me to look at something in particular?

**Comment by tajmone** [comment]
Thanks @RBastianini, I really appreciate it. There's no rush to complete the task, so we have ample time before the update will be published.

> Do you want me to look at something in particular?

Typos, left over Italian sentences (which were placed side-by-side with the English to aid translation) or untranslated terms, and possibly duplicate paragraphs (sometime I wrote alternative translations but then forgot to keep just one of them), and possibly check the examples sources and productions.

During the original editing I basically ported to markdown the original PML doc, which was an incomplete translation of the Italian version, and tried my best to polish the English, update it to match the Italian version (which was more recent) and complete the untranslated parts. I also adapted to English many examples which were originally in Italian, so the production output was manually filled in (not generated via Polygen).

If you spot anything worth amending, just open an Issue for it. 

I shall do all the editing work in a dev branch, and finally squash all the changes into a single commit once it's ready.

I'll probably ask both you and Alvise for a final proof-reading before merging into `master`, but that will be sometime in Autumn.

**Comment by RBastianini** [comment]
I did a first read through sections 1-2.4 (included) and I opened a couple of issues. I grouped some issues together instead of opening a ticket for each typo / suggestion. I did that so the issue tracker does not become crowded with very small tickets. Let me know if you prefer to split them further.

**Comment by tajmone** [comment]
> I did a first read through sections 1-2.4 (included) and I opened a couple of issues. 

thanks a lot Riccardo I really appreciated.

I've started working on some structural fixes to the repository and will then update the toolchain dependencies, and after that I'll finally be able to start working on the updated documents (it's worth doing the updates first, so we can spot any template/styles problems that might ensue).

> I grouped some issues together instead of opening a ticket for each typo / suggestion.

That's fine, I did that too. Also, these are often typos close to each other.

**Comment by tajmone** [comment]
# Final Proof-Reading Before Weekend

**ETA &rarr;** On __Sunday 13 September__ I'll be releasing `v1.1.1`.

Since this Issue was opened many typos were found and fixed, duplicate or original Italian left-over paragraphs removed, sentences wording improved and a few examples were fixed (thanks @RBastianini!).

I was planning to release `v1.1.1` during the weekend, so we can replace the _errors-ridden_ English document with a cleaner version, and benefit from the updated toolchain (text improvements will be handled in the second next release, see #36).

So, @alvisespano and @RBastianini, if you feel like going through the PML Spec docs (English and Italian) once more before the weekend, and point out any typos or things that need to be fixed, please go ahead. (I'll be going over both docs myself during the week.)

-------------------------------------------------------------------------------

__PS:__ I'll buzz Alvise via email 'cos I think he's not receiving GH notifications about repository activity.

**Comment by alvisespano** [comment]
Hey guys! Very nice work! I've been pretty busy lately. Looks like you're more committed to the project than me at the moment :D 
I've seen the new stuff, though just superficially due to time constraints. Go for the release anyway!

**Comment by RBastianini** [comment]
I think I might have some spare time ~tomorrow~ later today to read some more portions of the documentation. I haven't completed my first re-read, so I'll try to get through it instead of starting over.
