### ISSUE TITLE
Regole EBNF in Appendice

### ISSUE THREAD

**Issue by tajmone** [tajmone/polygen-docs#2]
Ciao @alvisespano,

Ho creato anche una sintass per EBNF di modo da colorare anche le regole EBNF riportate in [Appendice]. Il risultato lo trovo gradevole e più facile da leggere.

Mi sono permesso anche di ritoccare la EBNF delle [Regole lessicali] perché colorandone la sintassi mi sono reso conto che qualcosa non andava (nota, è la stessa regola in cui era andato perso un carattere). Prima era:

``` EBNF
Term ::= [a-z 0-9 '][a-z A-Z 0-9 ']*
      |  " [A-Z a-z 0-9 ( ) _ - ? . , ! : \ & # + * / % $ £ ` [ ] { } ~ @ ; : | < > = ^ ' \ "]* "
```

Il problema era alla fine della stringa: `\ "]* "` (seconda riga) — quelle virgolette tra il backslash e la parentesi quadra chiusa. Il parser di Highlight la vede come chiusura della stringa, e quindi con le virgolette successive (che dovrebbero essere quelle di chiusura) apre una nuova stringa che prosegue per svariate righe, ingarbugliando la sintassi.

L'ho cambiato in `\ ]* "`:

``` EBNF
Term ::= [a-z 0-9 '][a-z A-Z 0-9 ']*
      |  " [A-Z a-z 0-9 ( ) _ - ? . , ! : \ & # + * / % $ £ ` [ ] { } ~ @ ; : | < > = ^ ' \ ]* "
```

Dall'analisi dei sorgenti del Lexer, direi che è così che dovrebbe essere, ma ammetto di non conoscere a fondo la notazione EBNF, quindi spero di non aver fatto danni.

[regole lessicali]: http://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/draftwork/docs-src/Polyman_IT.html#sec:regole-lessicali "Live HTML preview via htmlpreview.github.io"

[Appendice]: https://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/draftwork/docs-src/Polyman_IT.html#sec:appendice "Live HTML preview via htmlpreview.github.io"

**Comment by alvisespano** [comment]
Va bene, a posto così. Si capisce. Considera che non è necessario che le regole lessicali e sintatiche siano perfettamente identiche a quelle di lexer e parser. Vedila così: il lexer ed il parser sono l'implementazione di tali regole, pertanto differiscono dalla specifica allo stesso modo in cui l'implementazione di un software differisce dalla sua specifica.
Infatti la grammatica del parser è più complessa della grammatica in appendice (ora raccolta da te nel file Polyman_inc_ebnf-abstract.markdown"). Lo stesso fenomeno accade anche col lexer.
