### ISSUE TITLE
Misc suggestions for section §2.4 (and nested paragraphs)

### ISSUE THREAD

**Issue by RBastianini** [tajmone/polygen-docs#26]
(**EDITED** by @tajmone)

- [x] In [§2.4](https://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/master/polygen-spec_EN.html#sec:unfolding) there is the following odd sentence:

    > Polygen provides a powerful unfolding system which, in general, allows to raise to the level of the current sequence a series of productions which would otherwise be folded (either by a subproduction or a non-terminal symbol) .

    I think that the Italian phrase structure was kept while translating the text into english:
    > Il Polygen dispone di un potente sottosistema di unfolding che, in generale, permette di portare al livello della sequenza corrente una serie di produzioni altrimenti raccolte in una sottoproduzione o da un simbolo non terminale.

    If we move some bits around the sentence flows better

    > Polygen provides a powerful unfolding system which, in general, allows to raise a series of productions (which would otherwise be folded either by a subproduction or a non-terminal symbol) to the level of the current sequence.

- [x] I'd also improve this other sentence by adding a verb to the secondary sentence:

    > Not every atom supports unfolding though, only those for which this operation makes sense: refer to section 5.1 for a syntactical formalization of this subset.

    > Not every atom supports unfolding though, only those for which this operation makes sense **do**: refer to section 5.1 for a syntactical formalization of this subset.

- [x] In [§2.4.1](https://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/master/polygen-spec_EN.html#sec:non-terminal-symbols), there is the following typo:

    > but this way we loose the original architecture, which folded all dog breeds within a dedicated non-terminal symbol, and increases drastically the amount of editing work required.

    `loose` -> `lose`

- [x] and the order of words should be adjusted for a better flow:

    > but this way we lose the original architecture, which folded all dog breeds within a dedicated non-terminal symbol, and drastically increases the amount of editing work required.

- [x] I also think this sentence can be improved:

    > In order to solve this problem (which is an instance of the wider problem of irregular distribution of probability affecting subproductions)

    I think that "broader" would be a better fit in place of "wider".

- [x]  [MOVED TO &rarr; Issue #32] ~~In [§2.4.2](https://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/master/polygen-spec_EN.html#sec:deeply-unfolded-subproductionss) the second example uses labels, a concept that has not yet been introduced to the reader. Maybe we can remove them from the example, so it becomes less confusing? (Actually, this suggestion also applies to the italian documentation).~~

- [x] In [§2.4.5](https://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/master/polygen-spec_EN.html#sec:unfolding-subproductions) there is the following typo:

    > As stated in section 2.8, deep unfolding leads to a subproduction where everything has been flatted out.

    `flatted` -> `flattened`.

**Comment by tajmone** [comment]
> In §2.4.2 the second example uses labels, a concept that has not yet been introduced to the reader. Maybe we can remove them from the example, so it becomes less confusing?

There are a couple of similar instances in both documents. I also found them confusing initially. It's also true that writing a specs doc without incurring in similar situations is not easy, but if it's avoidable I agree that it would be better to remove such examples and (if strictly required) provide a cross reference to the topic section (for the benefit of those who are re-reading the documents). 

I think that readers tend to spend some time studying the examples in order to make sense of what they've learned so far, so I'm totally in favor for this type of revision. What do you think @alvisespano?

>  (Actually, this suggestion also applies to the italian documentation).

Yes, this would be better moved to an independent Issue, so I can track it under the mliestone for both documents. But first let's see what @alvisespano thinks about these changes.

**Comment by alvisespano** [comment]
Ok for the typos and the modifications mentioned in the checklist above.
As for the wrong example with labels without having introduced them yet: yes, you're right, you can remove it. And replace it with something else without labels perhaps?
