### ISSUE TITLE
Manuale Inglese

### ISSUE THREAD

**Issue by tajmone** [tajmone/polygen-docs#3]
Ho "pusshato" la bozza inglese sulla branch di lavoro:

- http://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/draftwork/docs-src/polygen-spec_EN.html

(dovrei forse dire che l'ho «_spinta sul ramo_»? Ma italianizzando, si dice «_pushare_», «_pusshare_», «_pusciàre_»  o «_pucciare_»? Ma i "_pusher_" non sono quelli che ... ? (sì, insomma, hai capito.) Non ti rendi conto di quanto sia assurda e astrusa la terminologia di Git finché non provi a tradurla o maneggiarla in italiano.)

Per ora mi sono limitato a riformattare gli esempi e varie ripuliture tramite search-&-replace.

Da una lettura veloce direi che servirebbe anche una riaggiustatina al testo, alcune frasi suonano un po' forzate in inglese. Pur restando fedele al testo italiano, vorrei rifrasare in uno stile più inglese. Ho carta bianca in merito?

Invece, riguardo i termini tecnici che subentreranno con la traduzione delle sezioni mancanti, non mancherò di interpellarti.

**Comment by tajmone** [comment]
@alivsespano,

ho iniziato a tradurre le parti mancanti in inglese, e quindi anche i termini che non apparivano prima nel documento.

### Binding (forti, deboli, e sospensioni)

Se puoi dare un'occhiata alle sez. 2.0.10–2.0.11 per accertarti che la scelta dei termini è corretta:

https://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/draftwork/docs-src/polygen-spec_EN.html#sec:binding

Ero indeciso su come tradurre il secondo di questi due paragrafi:

> La produzione associata a `Frutto` viene sospesa e chiusa insieme all'ambiente corrente secondo le regole di scoping. Durante la generazione, alla prima occorrenza del simbolo `Frutto` in un ambiente discendente (od il medesimo, come nell'esempio) la produzione associata viene generata __una sola volta__ nell'ambiente chiuso assieme ad essa ed il risultato, immodificabile, della generazione risposto nell'ambiente; ogni successiva occorrenza dello stesso non terminale produrrà sempre lo stesso risultato.
> 
> Si badi che la prima generazione avviene in un ambiente in cui il simbolo non terminale in questione è associato alla chiusura, non ancora ad una sospensione: in tal modo è possibile fare uso di ricorsione anche definendo binding forti.


Alla fine ho scelto questa traduzione:

> Please note that during its first generation the non terminal is still associated to the closure of the environment where it's being generated, and not (yet) to its suspension: this allows the use of recursion in strong binding deinitions. 

e scartato quest'altra:

> Please note that the first generation of the non terminal occurs in an environment where the symbol is still associated to its closure, and not to its suspension: this allows the use of recursion in strong binding deinitions. 

... ma alla fine non ero sicuro di quale delle due esprimesse meglio il concetto. (la difficoltà consiste nel giostrare nella stessa frase i riferimenti all'ambiente, alla sua chiusura ed alla sua sospensione, senza rendere la frase troppo criptica).

**Comment by alvisespano** [comment]
Ti dico onestamente: a distanza di tanti anni non mi piace più quella
definizione. La riscrivo appena ho un minuto e te la mando. Non mi piace
più neanche il nome che do ai binding: ::= introduce rec-closure e :=
introduce lazyness. All'epoca usavo paroloni per riferirmi a queste entità;
oggi lo direi in modo meno criptico.

Il giorno mer 31 gen 2018 alle 19:33 Tristano Ajmone <
notifications@github.com> ha scritto:

**Comment by tajmone** [comment]
Ok. Riguarda solo i termini usati nell'inglese o anche nell'italiano?

### "arricchire" l'ambiente

Non so mai bene come tradurre "arricchire l'ambiente". A volte ho usato "__accrue__ the environment" (lett.: accrescere), altre "__enrich__ the environemnt" (traducendo alla lettera). Nessuno dei due suona bene.

Eppure, sento che mi sfugge un qualche termine più appropriato al contesto; è come se l'avessi sulla punta della lingua ma continua a scivolarmi via. 

Qualche idea?

**Comment by tajmone** [comment]
MI è tornato in mente: "**populate** the environment" — secondo me questo è il termine calzante per descrivere l'aggiunta di simboli all'ambiente. Ma se esistono già dei termini d'uso, ovviamente conviene rifarsi a quelli, però non ho trovato quali sono.

**Comment by alvisespano** [comment]
In inglese di solito si usa "populate the environment" oppure "bind to the
environment".
Scusami ma oggi e domani ho più di 100 orali, tutto il giorno, quindi non
riesco a risponderti bene.
Magari sabato provo a riscrivere la frase che dicevamo ieri.

Alvise


Il giorno 1 febbraio 2018 12:44, Tristano Ajmone <notifications@github.com>
ha scritto:

**Comment by tajmone** [comment]
### Bozza Inglese Terminata!

Ho appena terminato la revisione/traduzione del testo inglese — e quindi è ora passato alla Beta 1.

Voglio prendere una pausa e poi rileggerlo daccapo, per verificare errori di battitura e se alcune parti possono essere smussate.

Premesso che:

- Lo stile della mia traduzione dista quintillioni di anni luce da quello di Shakespear
- Il documento non vincerà un Pulitzer
- Il documento non assurgerà a stauts di "Stele di Rosetta" e madre di stile per tutti i manuali sul generis
- Ci saranno sicuremente errori di spelling ed anche alcuni abomini linguistici di varia natura

... ritengo comunque che si tratti di un lavoro decente.  Alla domanda:

_Una persona (magari non madre lingua inglese) che leggerà questo manuale, riuscirà a capire come funzionano le grammatiche Polygen?_

la risposta è: Sì! 

Credo anche che il testo sia abbastanza scorrevole, e di essere riuscito a smussare alcune parti arzigogolate, rendendole più fluide, e anche a stemperare un po' le parti fortemente tecniche.

### Correzioni Binding?

Avevi accennato a delle correzioni che volevi fare riguardo alla terminologia dei binding. 

Personalmente, trovo che le scelte attuali vadano bene:

- Closures: weak binding
- Suspensions: strong binding (o assignment)

Ovviamente: a meno che non siano tecnicamente sbagliate.

Comunque attendo tue istruzioni al riguardo.

E in ogni caso, prima di rendere definitivi i documenti attendo una tua conferma riguardo il testo inglese — a sto punto, farei che pubblicarli insieme, tanto l'inglese quanto l'italiano.

**Comment by alvisespano** [comment]
Ma sì dai, tieni la terminologia dei binding che avevo scelto all'epoca -
non ho voglia di pensarne una migliore :)
Il punto è questo: i weak binding sono rec-closure, mentre gli strong
binding sono assegnamenti lazy (o delayed computations, o suspended
computations) - questi sono i termini che si usano in letteratura. Però
tutto sommato credo che chiamare rec-closure i binding classici faccia solo
far confusione: ad un neofita può sembrare chissà cosa, quando invece in
realtà è molto chiara la loro semantica.

Il giorno 3 febbraio 2018 12:37, Tristano Ajmone <notifications@github.com>
ha scritto:

**Comment by tajmone** [comment]
Concordo. Alla fine, l'importante è che il lettore comprenda il linguaggio (senza dover impazzire per raggiungere lo scopo).

Io mi prenderei qualche giorno di pausa, così tu hai il tempo di dare un'ultima rilettura ai documenti, e io di prendere le dovute distanze dal testo (ora come ora, sono troppo coinvolto nel testo per essere obiettivo) per poter fare una rilettura a tabula rasa.

Nel frattempo, colgo l'occasione per rimettere  mano a un paio di progetti che ho lasciato in sospeso.

Dopodiché rileggo, ritocco eventuali refusi, e ripulisco i sorgenti markdown.

### Documenti Finali: Nome e Versione

Se ricordo bene, i documenti finali avranno la versione __1.1.0__.

Quanto ai nomi, riprendo quanto detto in [#1], e propongo:

Creare una copia dei i documenti finali in:

    archived/polygen-spec_en_1_1_0.html
    archived/polygen-spec_it_1_1_0.html

... dove la cartella `archived` conterrà lo storico di ogni versione del documento, per ogni lingua.

E nella root, invece, una copia di entrmbi i documenti senza numero di versione:

    polygen-spec.html
    polygen-spec.html

... di modo che la root contenga sempre una copia dell'ultima release del documento, in ciascuna lingua.

Vedrò di crare uno script che possa eseguire queste operazioni in automatico, così in futuro basterà un click per aggiornare il tutto a dovere.

### Sito GitHub Pages

Inoltre, come si era già accennato, potremmo attivare il sito di GitHub pages facendolo puntare alla cartella `docs` del repository, e lì includere una copia del documento in inglese, rinominata `index.html`, di modo che essa diventi un sito a pagina singola, visibile sul web.

(si dovrà solo aggiungere un file `.nojekyll` per disattivare Jekyll, il CMS di default di GitHub Pages, di modo che il sito sia in HTML statico.)

A tal fine vedrò anche di definire nello header YAML dei valori per i meta-tags HTML `description` e `keywords`, di modo che la pagina venga indicizzata a dovere.

[#1]: https://github.com/tajmone/polygen-docs/issues/1#issuecomment-358332485

**Comment by tajmone** [comment]
Ok, ho aggiornato il tutto e pubblicato (non mi sono ancora occupato del sito GitHub Pages, voglio rifletterci ancora sopra su come procedere).

Ho cancellato il branch "`draftwork`" — assicurati che anche la tua copia locale venga cancelleta, e che non lo ri-pushi sul repository per sbaglio.
