### ISSUE TITLE
Misc suggestions for section 2.7 - 2.10

### ISSUE THREAD

**Issue by RBastianini** [tajmone/polygen-docs#35]
- [x] In [§2.7](#id=sec:permutation) the secondary sentence of the first paragraph is missing the subject

    > Many spoken languages allow changing the order of some words (or groups of words) in a sentence without altering its original meaning; likewise, at a macroscopic level, sometimes is possible to swap the order of sentences within a phrase.

    should instead be

    > Many spoken languages allow changing the order of some words (or groups of words) in a sentence without altering its original meaning; likewise, at a macroscopic level, sometimes **it** is possible to swap the order of sentences within a phrase.

- [x] __(_REJECTED_)__ In the following sentence, the order of words can be altered for a more natural flow:

    > To avoid writing each and every variation of a sequence in which some atoms swap positions, you can enclose within curly brackets `{` and `}` the subproductions that need to be permutated.

    &rarr;

    > To avoid writing each and every variation of a sequence in which some atoms swap positions, you can enclose the subproductions that need to be permutated within curly brackets `{` and `}`.

- [x] I believe that the two following examples are incorrect. They are syntactically acceptable, but they do not produce the expected results, due to the use of unquoted commas `,`.

    ```
    S ::= {in 10 minutes}^, {at 3 o'clock}^, {"I" {will depart} {alone}} ;
    ```

    should instead be

    ```
    S ::= {in 10 minutes}^"," {at 3 o'clock}^"," {"I" {will depart} {alone}} ;
    ```

    and

    ```
    S ::= {in 10 minutes}^, {at 3 o'clock}^, ("I" {will depart} {alone}) ;
    ```

    should instead be

    ```
    S ::= {in 10 minutes}^"," {at 3 o'clock}^"," ("I" {will depart} {alone}) ;
    ```

    We can remove some of the punctuation signs by using dashes in place of commas, so we at least don't require to concatenate them to the preceding word, such as

    ```
    S ::= {in 10 minutes} "-" {at 3 o'clock} "-" {"I" {will depart} {alone}} ;
    ```

    and

    ```
    S ::= {in 10 minutes} "-" {at 3 o'clock} "-" ("I" {will depart} {alone}) ;
    ```

- [x] In §2.10, the first sentence can be rewritten in order to facilitate the reader:

    > Binding is, in general, a declarative construct that associates a series of productions to a non terminal symbol. Each binding introduces in the environment (see section 2.11) that association, and every production generated in that environment can refer to its non terminal symbol.

    &rarr;

    > Binding is, in general, a declarative construct that associates a series of productions to a non terminal symbol. Each binding introduces that association in the environment where it is declared (see section 2.11), and every production generated in that environment can refer to its non terminal symbol.

- [x] The two ending sentences in §2.10.1 can also be tweaked:

    > The production associated to Fruit does not undergo an immediate production but is closed together with the current environment according to scoping rules.

    &rarr;

    > The production associated to Fruit does not undergo an immediate **generation** but is closed together with the current environment according to scoping rules.

- [x] Also, there's a typo: `occurence` -> `occurrence` (actually this one is repeated a few times in the following paragraphs, consider doing a bulk replace).

- [x] In §2.10.2, I would personally replace the words in bold **a single time** with **just once**.

**Comment by tajmone** [comment]
> We can remove some of the punctuation signs by using dashes in place of commas, so we at least don't require to concatenate them to the preceding word

The problem is that we'd be replacing the commas with the minus sign `-` and not a real em-dash `—`, which would be a punctuation error. And I'm not sure how Polygen handles em-dashes in source files, due to the char (151) being outside the ASCII range, which makes it problematic if the source file is being encoded as UTF-8 (for it would be represented by a two code points sequence). If we stick to plain ASCII characters we avoid presenting the reader with examples that could lead to encoding problems (specially with beginners).

Unfortunately, in many modern editors and IDEs it's quite hard to work with ASCII/ISO-8859-1 encoding, for they easily break it and switch to UTF-8 if you paste some contents from an UTF-8 document (instead of converting the clipboard to ISO-8859-1). So, I suggest keeping the commas to avoid similar issues.

**Comment by tajmone** [comment]
> In the following sentence, the order of words can be altered for a more natural flow:
>
> > To avoid writing each and every variation of a sequence in which some atoms swap positions, you can enclose within curly brackets `{` and `}` the subproductions that need to be permutated.
>
> > To avoid writing each and every variation of a sequence in which some atoms swap positions, you can enclose the subproductions that need to be permutated within curly brackets `{` and `}`.

Although the latter flows slightly better it introduces some semantic ambiguity, which causes some degree of strain on the reader to resolve it.

**Comment by tajmone** [comment]
The commas problem in §2.7, mentioned by @RBastianini, also affects the Italian document; so I've created an issue for it: #37
