### ISSUE TITLE
Suggestions for sections 2.11 up to section 3

### ISSUE THREAD

**Issue by RBastianini** [tajmone/polygen-docs#39]
- [ ] In **§2.11.2** and following I see more occurrences of the "bare" typo. I remember that you @tajmone mentioned doing a search and replace, so maybe I'm not looking at the [latest revision](https://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/dev1.1.1_EN/polygen-spec_EN.html#sec:static-lexical-scoping)?

In **§2.11.3** there are many Italian leftover paragraphs in the documentation:
- [ ] "Si badi infine che [...]",
- [ ] "L'occorrenza di `X` [...]",
- [ ] "Analogamente in presenza [...]".

Also, still in §2.11.3 I think there is a typo:
> The occurence of `X` inside the second inserted binding

should be

> The occur**r**ence of `X` inside the second **nested** biding

- [ ] I still see the "occurence" typo in the docs. :eyes:

In **§2.12**, there are the following typos:
- [ ] "burer" -> "burden"
- [ ] I would also suggest rephrasing this sentence
> This feature — which is operationally equivalent to using labels and selections, but less verbose — allows to express in an extremely concise way groups of suffixes, declinations, conjucations, etc. 

to

> This feature — which is operationally equivalent to using labels and selections, but less verbose — allows to express groups of suffixes, declinations, conjucations, etc, in an extremely concise way

- [ ] Leftover Italian paragraph "È importante capire che [...]"

In **§2.13**:
- [ ] Leftover Italian paragraph: "Si potrebbe ritenere ragionevole [...]".
- [ ] I think that the sentence would sound better
> One might have — quite reasonably so — expected to see

as

> One might have — quite reasonably — expected to see

or as 

> One might have expected — quite reasonably — to see

I can't really offer an explanation to why, but I believe it flows better.

**Comment by tajmone** [comment]
> maybe I'm not looking at the latest revision?

No, definitely not. See #27 for the correct preview links.

**Comment by tajmone** [comment]
I've now integrated all the suggestions that weren't already dealt with.
