### ISSUE TITLE
PML: Improve Permutation Examples in §2.7

### ISSUE THREAD

**Issue by tajmone** [tajmone/polygen-docs#8]
In [§2.7 _Permutation_][§2.7] of both the English and Italian PML docs, two consecutive examples tend to appear to have identical  Polygen sources, whereas in fact the second example employs round braces instead of curly ones (i.e. `("I" {will depart} {alone}) ;` vs `{"I" {will depart} {alone}} ;`):

> **EXAMPLE**
> 
> ```
> S ::= {in 10 minutes}^, {at 3 o'clock}^, {"I" {will depart} {alone}} ;
> ```
> 
> **PRODUCES**
> 
> ```
> in 10 minutes, at 3 o'clock, I will depart alone
> at 3 o'clock, in 10 minutes, I will depart alone
> in 10 minutes, I will depart alone, at 3 o'clock
> at 3 o'clock, I will depart alone, in 10 minutes
> I will depart alone, in 10 minutes, at 3 o'clock
> I will depart alone, at 3 o'clock, in 10 minutes
> in 10 minutes, at 3 o'clock, I alone will depart
> at 3 o'clock, in 10 minutes, I alone will depart
> in 10 minutes, I alone will depart, at 3 o'clock
> at 3 o'clock, I alone will depart, in 10 minutes
> I alone will depart, in 10 minutes, at 3 o'clock
> I alone will depart, at 3 o'clock, in 10 minutes
> ```
> **EXAMPLE**
> 
> `S ::= {in 10 minutes}^, {at 3 o'clock}^, ("I" {will depart} {alone}) ;`
> **PRODUCES**
> 
> ```
> in 10 minutes, at 3 o'clock, I will depart alone
> at 3 o'clock, in 10 minutes, I will depart alone
> in 10 minutes, at 3 o'clock, I alone will depart
> at 3 o'clock, in 10 minutes, I alone will depart
> ```

Since it's quite possible that the average reader might not detect the subtle difference between the use of round/curly braces in the two source examples (they look similar, especially with medium font sizes) it might be worth adding an explicit note to highlight the difference between the two examples.

[§2.7]: https://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/master/polygen-spec_EN.html#sec:permutation "Live Preview"

**Comment by tajmone** [comment]
Che ne pensi @alvisespano? 

Sebbene si tratta solo di un dettaglio, mi rendo conto che ogni volta che rileggo quella sezione ci metto qualche minuto ad accorgermi della presenza di parentesi tonde nel secondo sorgente, e trarre un senso dal secondo esempio. 

Questo avviene nonostante abbia letto e riletto il documento più e più volte, in entrambe le lingue, quindi immagino che per chi legge il documento la prima volta debba essere ancor più difficile cogliere la differenza tra i due esempi — soprattutto perché le parentesi grafe sono molto simili a quelle tonde nei font monospace, a quelle dimensioni di carattere.

Aggiungere una frase di avvertimento che indichi al lettore l'uso di parentesi differenti nei due esempi ci costerebbe poco e nulla, ma potrebbe fare una grande differenza per il lettore.

**Comment by alvisespano** [comment]
Sono d'accordo con te: non è così chiaro. Cambiare esempio non è semplice: è praticamente un minimal example. Come dici tu, conviene spiegare meglio nel testo: sottolineare che sono graffe quelle parentesi; e nel secondo esempio rimarcare che sono tonde quelle più a destra.

**Comment by tajmone** [comment]
Ottimo, allora provvedo subito. Magari uso uno degli appositi blocchi per le note, che sono carini da vedere e, al contempo, sono un "contenuto laterale" al testo.

**Comment by tajmone** [comment]
OK, fatto!

Spero che il testo della nota vada bene.

-------------------------------------------------------------------------------

Nell'inglese:

> **BEWARE!** — The two examples below might look the same at first glance, but their endings are different:
>
> - the first example uses braces:
>    + `{"I" {will depart} {alone}} ;`
> - the other one uses parentheses:
>    + `("I" {will depart} {alone}) ;`


-------------------------------------------------------------------------------

Nell'italiano:

> **ATTENZIONE!** — I due esempi che seguono posso sembrare identici di primo acchito, ma differiscono nella parte finale:
>
> - il primo impiega parentesi graffe:
>    + `{{io} {partiro'} solo} ;`
> - il secondo parentesi tonde:
>    + `({io} {partiro'} solo) ;`
